apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2024-10-12T03:17:29Z"
  name: manage-services-global
  resourceVersion: "81054"
  uid: ad4cca05-927b-429e-93d2-cdfad36ce5ec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: services-cluster-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
